apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      initContainers:
      - name: wait-for-b
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -qO- http://service-b/health; do echo waiting for service-a; sleep 2; done;']
      containers:
      - name: service-c
        image: dmarshaltu/pocsimple:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  selector:
    app: service-c
  ports:
  - port: 80
    targetPort: 80