apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  annotations:
    helm.sh/hook-weight: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      initContainers:
      - name: wait-for-a
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -qO- http://service-a/health; do echo waiting for service-a; sleep 2; done;']
      containers:
      - name: service-b
        image: nginx:alpine
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - port: 80
    targetPort: 80